name: Gerar Relat칩rio em R

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar reposit칩rio
        uses: actions/checkout@v3

      - name: Instalar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Instalar pacotes R necess치rios
        run: |
          Rscript -e 'install.packages("rmarkdown", repos="https://cloud.r-project.org")'

      - name: Gerar HTML a partir do Rmd
        run: |
          Rscript -e 'rmarkdown::render("relatorio.Rmd", output_dir = "docs")'

      - name: Commit e push do HTML
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/
          git commit -m "Atualiza relat칩rio HTML"
          git push
